name: CI Worker

on:
  pull_request:
    branches: 
      - worker-prod
      - main
    paths:
      - "worker-mail/**"

jobs:
  typecheck:
    name: TypeCheck Worker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker-mail

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: TypeCheck
        run: bun run typecheck
